#!/usr/bin/env bash
# sim/workload/scripts/run.sh
#
# Project kill-switch benchmark.
#
# Run on a Framework Desktop (Strix Halo, 128 GB LPDDR5X-8000) with:
#   - Linux kernel >=6.18.4 (gfx1151 stability)
#   - ROCm >=7.0 configured per AMD's Strix Halo guide
#   - ollama installed
#
# If any min-target row in the table reports FAIL, the project pauses
# until the gap is closed (newer kernel/ROCm) or the target is revised
# down with explicit user buy-in.
#
# Usage:
#   ./sim/workload/scripts/run.sh                # full suite
#   ./sim/workload/scripts/run.sh qwen           # one model only
#
# Output:
#   sim/workload/results/<timestamp>/REPORT.md   (commit this)
#   sim/workload/results/<timestamp>/raw/*.log

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKLOAD_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
TS="$(date -u +%Y%m%dT%H%M%SZ)"
OUT_DIR="${WORKLOAD_DIR}/results/${TS}"
RAW_DIR="${OUT_DIR}/raw"
mkdir -p "${RAW_DIR}"

PROMPT="Explain the OSI model in two sentences."
FILTER="${1:-all}"

# (model, tag, min_tok_s, stretch_tok_s)
MODELS=(
  "qwen3-30b-a3b|qwen3:30b-a3b-q4_K_M|30|50"
  "llama33-70b|llama3.3:70b-instruct-q4_K_M|4|7"
  "gpt-oss-120b|gpt-oss:120b-q4_K_M|25|35"
  "mistral-7b|mistral:7b-instruct-q5_K_M|60|90"
)

# --- Preflight -----------------------------------------------------------------

if ! command -v ollama >/dev/null 2>&1; then
  echo "ERROR: ollama not installed. See https://ollama.com/download"
  exit 1
fi

if ! command -v rocm-smi >/dev/null 2>&1; then
  echo "WARNING: rocm-smi not on PATH — temperature column will be blank."
fi

KERNEL="$(uname -r)"
ROCM_VER="$(rocminfo 2>/dev/null | awk -F: '/Runtime Version/ {print $2}' | xargs || echo unknown)"

# --- Per-model benchmark --------------------------------------------------------

run_one() {
  local short="$1" tag="$2" min="$3" stretch="$4"
  local log="${RAW_DIR}/${short}.log"

  echo "=== ${short} (${tag}) ==="

  # Pull if not present
  ollama list | awk '{print $1}' | grep -qx "${tag}" || ollama pull "${tag}"

  # Background temp logger (best-effort)
  local temp_log="${RAW_DIR}/${short}.temp.csv"
  ( while true; do
      printf '%s,%s\n' "$(date -u +%s)" "$(rocm-smi --showtemp --csv 2>/dev/null | tail -n +2 | head -n1 | awk -F, '{print $2}')"
      sleep 1
    done ) > "${temp_log}" 2>/dev/null &
  local temp_pid=$!
  trap "kill ${temp_pid} 2>/dev/null || true" EXIT

  # The actual run
  ollama run "${tag}" --verbose <<<"${PROMPT}" 2>&1 | tee "${log}"

  kill ${temp_pid} 2>/dev/null || true
  trap - EXIT

  # Extract eval rate from ollama --verbose output
  local rate
  rate="$(awk '/eval rate:/ {print $3}' "${log}" | tail -n1)"
  rate="${rate:-0}"

  local peak_temp
  peak_temp="$(awk -F, 'NR>0 && $2!="" {if ($2+0 > max) max=$2+0} END {print (max ? max : "n/a")}' "${temp_log}" 2>/dev/null || echo n/a)"

  local verdict="FAIL"
  awk -v r="${rate}" -v m="${min}" 'BEGIN{exit !(r+0 >= m+0)}' && verdict="PASS"

  printf '%s|%s|%s|%s|%s|%s\n' "${short}" "${rate}" "${min}" "${stretch}" "${peak_temp}" "${verdict}" \
    >> "${RAW_DIR}/summary.psv"
}

for entry in "${MODELS[@]}"; do
  IFS='|' read -r short tag min stretch <<<"${entry}"
  if [[ "${FILTER}" != "all" && "${FILTER}" != "${short%-*}" ]]; then
    continue
  fi
  run_one "${short}" "${tag}" "${min}" "${stretch}"
done

# --- Build REPORT.md -----------------------------------------------------------

REPORT="${OUT_DIR}/REPORT.md"
{
  echo "# Workload validation — REPORT"
  echo
  echo "Run: \`${TS}\`"
  echo
  echo "**Hardware:** Framework Desktop, Strix Halo, 128 GB LPDDR5X-8000"
  echo "**Kernel:** \`${KERNEL}\`"
  echo "**ROCm:** \`${ROCM_VER}\`"
  echo "**Prompt:** *${PROMPT}*"
  echo
  echo "| Model | Min target | Measured tok/s | Stretch | Peak T (°C) | Verdict |"
  echo "|---|---|---|---|---|---|"
  while IFS='|' read -r short rate min stretch peak verdict; do
    printf '| %s | %s | %s | %s | %s | %s |\n' \
      "${short}" "${min} tok/s" "${rate}" "${stretch}" "${peak}" \
      "$( [[ "${verdict}" == PASS ]] && echo "✅ PASS" || echo "❌ FAIL" )"
  done < "${RAW_DIR}/summary.psv"
  echo
  if grep -q '|FAIL$' "${RAW_DIR}/summary.psv"; then
    echo "## Verdict: ❌ THESIS FAILED"
    echo
    echo "One or more min targets missed. See raw logs in \`raw/\`."
    echo "Project pauses for explicit triage per [\`sim/workload/README.md\`](../../README.md)."
  else
    echo "## Verdict: ✅ THESIS CONFIRMED"
    echo
    echo "All min targets met. Proceed to motherboard schematic capture (Phase 2)."
  fi
  echo
  echo "---"
  echo "*Generated by* \`sim/workload/scripts/run.sh\`"
} > "${REPORT}"

echo
echo "REPORT written: ${REPORT}"
echo
cat "${REPORT}"

# Symlink latest for convenience
ln -sfn "${TS}" "${WORKLOAD_DIR}/results/latest"
